#! /bin/bash -e

docker build -t monica-sandstorm:latest .
ctr=$(buildah from docker-daemon:monica-sandstorm:latest)
mnt=$(buildah mount $ctr)

sed --in-place='' \
    --expression='s,( sourcePath = "/.*",( sourcePath = "'"$mnt"'",' \
    sandstorm-pkgdef.capnp

sed --in-place='' \
    --expression="s/MONICA_VERSION/$(cat $mnt/monica_version)/" \
    sandstorm-pkgdef.capnp
